name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

# ======================
# FRONTEND TEST
# ======================
  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run frontend test
        run: |
          echo "Running frontend test..."
          node frontend/test/test.js

# ======================
# BACKEND TEST
# ======================
  backend-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend
        working-directory: backend
        run: npm install

      - name: Run backend test
        working-directory: backend
        run: npm test


  selenium-test:
    runs-on: ubuntu-latest
    needs: backend-test
  
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
  
    env:
      MONGO_URI: mongodb://localhost:27017/pc_config_db
  
    steps:
      - uses: actions/checkout@v4
  
      - uses: actions/setup-node@v4
        with:
          node-version: 18
  
      - name: Install dependencies
        run: |
          npm install
          npm install selenium-webdriver
          npm install -g wait-on
  
      - name: Start backend
        run: node backend/server.js &
  
      - name: Wait for backend
        run: npx wait-on http://localhost:5000 --timeout 30000
  
      - name: Run Selenium Test
        run: node selenium-test.js


# ======================
# DOCKER BUILD
# ======================
  docker-build:
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test]

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t pc-config-app ./backend

# ======================
# DEPLOY (Render trigger placeholder)
# ======================
  deploy:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - name: Deploy step
        run: echo "Deploying to Render..."
